version: "3"
services:

  jupyter:
    image: kaikun/fonduer-electricity
    environment:
      PGPASSWORD: venron
    ports:
      - "8888:8888"
    links:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: venron
    volumes:
      - ./init:/docker-entrypoint-initdb.d
